export const disabledPermissions = {
	create: [
		'crm.leads.create.department.disabled-any',
		'crm.leads.create.mine.disabled-any',
		'crm.companies.create.department.disabled-any',
		'crm.companies.create.mine.disabled-any',
		'crm.contacts.create.department.disabled-any',
		'crm.contacts.create.mine.disabled-any',
		'crm.deals.create.department.disabled-any',
		'crm.deals.create.mine.disabled-any',
		'crm.activity.create.department.disabled-any',
		'crm.activity.create.mine.disabled-any',
		'crm.uspacy_calls.create.mine.disabled-any',
		'crm.uspacy_calls.create.department.disabled-any',
		'hub.uspacy_journal.create.allowed.disabled-any',
		'hub.uspacy_journal.create.mine.disabled-any',
		'hub.uspacy_journal.create.department.disabled-any',
		'hrm.activity.create.department.disabled-any',
		'hrm.activity.create.mine.disabled-any',
		'hrm.employee.create.mine.disabled-any',
		'hrm.employee.create.department.disabled-any',
		'hrm.department.create.mine.disabled-any',
		'hrm.department.create.department.disabled-any',
		'tasks.task.create.department.disabled-any',
		'tasks.task.create.mine.disabled-any',
	],
	edit: [
		'hub.uspacy_journal.edit.allowed.disabled-any',
		'hub.uspacy_journal.edit.mine.disabled-any',
		'hub.uspacy_journal.edit.department.disabled-any',
	],
	view: ['hub.uspacy_journal.view.mine.disabled-any', 'hub.uspacy_journal.view.department.disabled-any'],
	delete: [
		'crm.uspacy_calls.delete.allowed.disabled-any',
		'crm.uspacy_calls.delete.mine.disabled-any',
		'crm.uspacy_calls.delete.department.disabled-any',
		'hub.uspacy_journal.delete.allowed.disabled-any',
		'hub.uspacy_journal.delete.mine.disabled-any',
		'hub.uspacy_journal.delete.department.disabled-any',
	],
};
