export const disabledPermissions = {
	create: [
		'crm.leads.create.department.disabled-any',
		'crm.leads.create.mine.disabled-any',
		'crm.companies.create.department.disabled-any',
		'crm.companies.create.mine.disabled-any',
		'crm.contacts.create.department.disabled-any',
		'crm.contacts.create.mine.disabled-any',
		'crm.deals.create.department.disabled-any',
		'crm.deals.create.mine.disabled-any',
		'crm.activity.create.department.disabled-any',
		'crm.activity.create.mine.disabled-any',
		'crm.uspacy_calls.create.allowed.disabled-any',
		'crm.uspacy_calls.create.mine.disabled-any',
		'crm.uspacy_calls.create.department.disabled-any',
		'hrm.activity.create.department.disabled-any',
		'hrm.activity.create.mine.disabled-any',
		'hrm.employee.create.mine.disabled-any',
		'hrm.employee.create.department.disabled-any',
		'tasks.task.create.department.disabled-any',
		'tasks.task.create.mine.disabled-any',
	],
	edit: ['crm.uspacy_calls.edit.department.disabled-any'],
	view: ['crm.uspacy_calls.view.department.disabled-any'],
	delete: [
		'crm.uspacy_calls.delete.allowed.disabled-any',
		'crm.uspacy_calls.delete.mine.disabled-any',
		'crm.uspacy_calls.delete.department.disabled-any',
	],
};
