export const disabledPermissions = {
	create: [
		'crm.leads.create.department.disabled-any',
		'crm.leads.create.mine.disabled-any',
		'crm.companies.create.department.disabled-any',
		'crm.companies.create.mine.disabled-any',
		'crm.contacts.create.department.disabled-any',
		'crm.contacts.create.mine.disabled-any',
		'crm.deals.create.department.disabled-any',
		'crm.deals.create.mine.disabled-any',
		'crm.activity.create.department.disabled-any',
		'crm.activity.create.mine.disabled-any',
		'crm.call.create.disabled.disabled-any',
		'crm.call.create.mine.disabled-any',
		'crm.call.create.allowed.disabled-any',
		'hrm.activity.create.department.disabled-any',
		'hrm.activity.create.mine.disabled-any',
		'hrm.employee.create.mine.disabled-any',
		'hrm.employee.create.department.disabled-any',
		'tasks.task.create.department.disabled-any',
		'tasks.task.create.mine.disabled-any',
	],
	edit: ['crm.call.edit.disabled.disabled-any', 'crm.call.edit.mine.disabled-any', 'crm.call.edit.allowed.disabled-any'],
	view: ['crm.call.view.disabled.disabled-any', 'crm.call.view.mine.disabled-any', 'crm.call.view.allowed.disabled-any'],
	delete: ['crm.call.delete.disabled.disabled-any', 'crm.call.delete.mine.disabled-any', 'crm.call.delete.allowed.disabled-any'],
};
