/* eslint-disable quotes */
/* eslint-disable max-len */
import { createAsyncThunk } from '@reduxjs/toolkit';
import { uspacySdk } from '@uspacy/sdk';

export const getForms = createAsyncThunk('forms/getForms', async (params?: Record<string, string | number>) => {
	try {
		// const res = (await uspacySdk.resourcesService.getResources('form', params)).data;
		return [
			{
				userId: 1,
				portal: 'stage5.staging.uspacy.tech',
				name: 'all predefined',
				type: 'form',
				config: {
					crmEntity: 'contact',
					fields: [
						{
							fieldCode: 'email',
							type: 'email',
							label: 'Електронна пошта',
							hint: 'Електронна пошта',
							secondHintText: '',
							placeholder: '',
							required: true,
							selected: true,
							field: {
								name: 'Email',
								code: 'email',
								entity_reference_id: '',
								type: 'email',
								required: false,
								editable: true,
								show: true,
								hidden: false,
								multiple: true,
								system_field: true,
								base_field: true,
								sort: '',
								default_value: '',
								tooltip: '',
								display_in_tabs: false,
								entity: 'contact',
							},
							order: 1,
						},
						{
							fieldCode: 'phone',
							type: 'phone',
							label: 'Телефон',
							hint: 'Телефон',
							secondHintText: '',
							placeholder: '',
							required: true,
							selected: true,
							field: {
								name: 'Phone',
								code: 'phone',
								entity_reference_id: '',
								type: 'phone',
								required: false,
								editable: true,
								show: true,
								hidden: false,
								multiple: true,
								system_field: true,
								base_field: true,
								sort: '',
								default_value: '',
								tooltip: '',
								display_in_tabs: false,
								entity: 'contact',
							},
							order: 3,
						},
						{
							fieldCode: 'birthdate',
							type: 'formTextData',
							label: 'Дата народження',
							hint: 'Date of birth',
							secondHintText: '',
							placeholder: '',
							required: true,
							selected: true,
							field: {
								name: 'Date of birth',
								code: 'birthdate',
								entity_reference_id: '',
								type: 'datetime',
								required: false,
								editable: true,
								show: true,
								hidden: false,
								multiple: false,
								system_field: false,
								base_field: false,
								sort: 180,
								default_value: '',
								tooltip: '',
								display_in_tabs: false,
								entity: 'contact',
							},
							order: 4,
						},
						{
							fieldCode: 'divider',
							type: 'formTextData',
							label: '',
							hint: '',
							placeholder: '',
							selected: true,
							order: 8,
						},
						{
							fieldCode: 'vibir_diyi_ua_gdpr',
							type: 'formTextData',
							label: 'Вибір дії',
							hint: 'Вибір дії UA GDPR',
							secondHintText: '',
							placeholder: '',
							required: true,
							selected: true,
							field: {
								name: 'Вибір дії UA GDPR',
								code: 'vibir_diyi_ua_gdpr',
								entity_reference_id: '',
								type: 'list',
								required: true,
								editable: true,
								show: true,
								hidden: false,
								multiple: false,
								system_field: false,
								base_field: false,
								sort: '',
								default_value: '',
								tooltip: 'Введіть значення Вибір дії',
								display_in_tabs: false,
								values: [
									{
										title: 'Надавати доступ до моїх персональних даних, які вона обробляє, а також надала мені інформацію в обсязі, зазначеному в розділі 15 пункту 1 постанови.',
										value: 'nadavati_dostup_do_moyih_personalnih_danih_yaki_vona_obroblyaie_a_takozh_nadala_meni_informaciyu_v_obsyazi_zaznachenomu_v_rozdili_15_punktu_1_postanovi',
										color: '#9155FD',
										sort: 10,
										selected: false,
									},
									{
										title: 'Виправити неточності в даних відповідно до розділу 16 постанови в обсязі, зазначеному нижче.',
										value: 'vipraviti_netochnosti_v_danih_vidpovidno_do_rozdilu_16_postanovi_v_obsyazi_zaznachenomu_nizhche',
										color: '#FF4C51',
										sort: 20,
										selected: false,
									},
									{
										title: 'Видалити всі мої персональні дані відповідно до розділу 17 постанови.',
										value: 'vidaliti_vsi_moyi_personalni_dani_vidpovidno_do_rozdilu_17_postanovi',
										color: '#32BAFF',
										sort: 30,
										selected: false,
									},
									{
										title: 'Обмежити обробку моїх персональних даних відповідно до розділу 18 постанови',
										value: 'obmezhiti_obrobku_moyih_personalnih_danih_vidpovidno_do_rozdilu_18_postanovi',
										color: '#9155FD',
										sort: 40,
										selected: false,
									},
									{
										title: 'Передавати мої персональні дані іншому адміністратору, зазначеному нижче, відповідно до розділу 20 постанови.',
										value: 'peredavati_moyi_personalni_dani_inshomu_administratoru_zaznachenomu_nizhche_vidpovidno_do_rozdilu_20_postanovi',
										color: '#FF4C51',
										sort: 50,
										selected: false,
									},
								],
								entity: 'contact',
							},
							order: 6,
						},
						{
							fieldCode: 'im_ya_gdpr',
							type: 'formTextData',
							label: 'ПІБ',
							hint: "Ім'я GDPR",
							secondHintText: '',
							placeholder: '',
							required: true,
							selected: true,
							field: {
								name: "Ім'я GDPR",
								code: 'im_ya_gdpr',
								entity_reference_id: '',
								type: 'string',
								required: true,
								editable: true,
								show: true,
								hidden: false,
								multiple: false,
								system_field: false,
								base_field: false,
								sort: '',
								default_value: '',
								tooltip: '',
								display_in_tabs: false,
								entity: 'contact',
							},
							order: 2,
						},
						{
							fieldCode: 'uf_crm_1582185415',
							type: 'formTextData',
							label: 'Моя відповідь',
							hint: 'Короткое описание',
							secondHintText: '',
							placeholder: '',
							required: true,
							selected: true,
							field: {
								name: 'Короткое описание',
								code: 'uf_crm_1582185415',
								entity_reference_id: '',
								type: 'textarea',
								required: false,
								editable: true,
								show: true,
								hidden: false,
								multiple: false,
								system_field: false,
								base_field: false,
								sort: 1260,
								default_value: '',
								tooltip: '',
								display_in_tabs: false,
								entity: 'contact',
							},
							order: 9,
						},
					],
					other: [
						{
							isOther: true,
							order: 2,
							fieldCode: 'form',
							isOutsideSort: true,
						},
						{
							isOther: true,
							order: 7,
							fieldCode: 'header',
							value: '<p class="PlaygroundEditorTheme__paragraph" dir="ltr" style="text-align: left;"><span style="font-size: 14px; white-space: pre-wrap;">Також, прошу надiслати менi iнформацiю про вжитi щодо цього заходи протягом термiну встановленого розд.12 абз.3 Загальної Постанови Про охорону персональних даних письмово на вищевказану адресу/ на електронну адресу.</span></p><p class="PlaygroundEditorTheme__paragraph" dir="ltr" style="text-align: left;"><span style="font-size: 14px; white-space: pre-wrap;">Причини подання заяви: вказання неточних даних, що пiдлягають виправленню; вказання адмiнiстратора, котрому необхiдно передати данi; додаткова iнформацiя:</span></p>',
							ico: {
								key: null,
								ref: null,
								_owner: null,
							},
							previewTitle: 'Заголовок',
							selected: true,
						},
						{
							isOther: true,
							fieldCode: 'addFieldButton',
							order: 10,
						},
						{
							isOther: true,
							fieldCode: 'submitButton',
							previewTitle: '',
							buttonSettings: {
								background: '#32BAFF',
								text: 'Надіслати',
								showIco: true,
								ico: 'ButtonIco',
							},
							order: 11,
						},
						{
							isOther: true,
							order: 5,
							fieldCode: 'subheader',
							value: '<p class="PlaygroundEditorTheme__paragraph" dir="ltr" style="text-align: left;"><span style="font-size: 14px; white-space: pre-wrap;">Даною заявою застосовую своє право, гарантоване Постановою Європейського Парламенту та Ради № 2016/679 Про охорону фiзичних осiб в зв`язку з обробкою персональних даних та про вiльне пересування цих даних, а також про скасування Директиви95/46/ES (далі – «Постанова») і прошу, щоб компанія: INFOBUS s.r.o., з юридичною адресою U Sluncové 666/12a, 186 00 Прага 8, Чеська Республіка, реєстраційний номер 24245224, зареєстрована в Торговому реєстрі, який ведеться Міським судом у Празі, в розділі:</span></p>',
							ico: {
								key: null,
								ref: null,
								_owner: null,
							},
							previewTitle: 'Підзаголовок',
							selected: true,
						},
						{
							isOther: true,
							order: 1,
							fieldCode: 'banner',
							value: 'https://storage.googleapis.com/bootstrap-59-1cdyr/65/00000000000000014965/15/bd/15bd10896cec5a312dcdf0fb1b39194e.png',
							ico: {
								key: null,
								ref: null,
								_owner: null,
							},
							previewTitle: 'Банер',
							selected: true,
							isOutsideSort: true,
						},
					],
					after: {
						showMessage: true,
						fields: [
							{
								order: 0,
								fieldCode: 'logo',
								formLogoValue: 'IcoAfterScreen5',
								formLogoColor: '#32BAFF',
							},
							{
								order: 1,
								fieldCode: 'header',
								value: '<p class="PlaygroundEditorTheme__paragraph" style="text-align: center;"><b><strong class="PlaygroundEditorTheme__textBold" style="font-size: 18px; white-space: pre-wrap;">Успішно надіслано!</strong></b></p>',
								previewTitle: 'Заголовок',
							},
						],
						redirectUrl: null,
						timeBeforeRedirect: null,
					},
					design: {
						generalColors: {
							pageBg: '#2a3647',
							formBg: '#d8e0e8',
						},
						button: {
							style: 'contained',
							borderRadius: 6,
							size: 'medium',
							textSize: 16,
							textLetterSpacing: 'standard',
						},
						fields: {
							style: 'outlined',
							borderRadius: 6,
							size: 'small',
							textSize: 14,
							hideFieldLabel: false,
						},
						additional: {
							formPosition: 'center',
							showUspacyBrand: false,
						},
						otherSettings: {
							logoIsInTheFormHeader: false,
							currenciesOptions: ['UAH', 'USD', 'EUR'],
						},
					},
					predefinedFields: [
						{
							type: 'owner',
							value: 1,
						},
						{
							type: 'source',
							value: 'gdpr',
						},
					],
				},
				active: true,
				entryPoint: 'https://application-stage-bucket.s3.eu-west-1.amazonaws.com/69/78/6978b511e95ce7086dcbaa1c/forms.js',
				id: '6978b511e95ce7086dcbaa1c',
				created_at: 1769518353,
				updated_at: 1769533006,
			},
		];
	} catch (e) {
		return e;
	}
});
