import { IEntityMainData } from '@uspacy/sdk/lib/models/crm-entities';
import { IField } from '@uspacy/sdk/lib/models/field';

export const API_PREFIX_FILES = '/files/v1';
export const API_PREFIX_SETTINGS = '/settings/v1';
export const TWO_WEEK_TIME_VALUE = 1123200;

export const idColumn: IField = {
	name: 'number_',
	code: 'id_column',
	required: false,
	editable: false,
	show: false,
	hidden: true,
	multiple: false,
	type: 'id_column',
	system_field: true,
	sort: '',
	default_value: '',
};

export const idColumnField: IField = {
	...idColumn,
};

export const stageField: IField = {
	name: 'stage',
	code: 'kanban_stage_id',
	required: false,
	editable: false,
	show: true,
	hidden: false,
	multiple: false,
	type: 'stage',
	sort: '',
	default_value: '',
	system_field: false,
};

export const dealsField: IField = {
	name: 'deals',
	code: 'deals',
	required: false,
	editable: false,
	show: false,
	hidden: true,
	multiple: false,
	type: 'deals_filter',
	system_field: true,
	sort: '',
	default_value: '',
};

export const taskField: IField = {
	name: 'tasks',
	code: 'tasks',
	required: false,
	editable: false,
	show: false,
	hidden: true,
	multiple: false,
	type: 'tasks_filter',
	system_field: true,
	sort: '',
	default_value: '',
};

export const requisiteField: IField = {
	name: 'requisite',
	code: 'requisites',
	required: false,
	editable: false,
	show: true,
	hidden: false,
	multiple: false,
	type: 'requisite',
	system_field: true,
	base_field: true,
	sort: '',
};

export const headField: IField = {
	name: 'head',
	code: 'head',
	required: false,
	editable: false,
	show: false,
	hidden: true,
	multiple: false,
	type: 'user_id',
	system_field: true,
	sort: '',
	default_value: '',
};

export const OTHER_DEFAULT_FIELDS = {
	openDatePicker: false,
	search: '',
	page: 0,
	perPage: 0,
	boolean_operator: 'AND',
	table_fields: [],
	sortModel: [],
};

export enum EntityIds {
	leads = '1',
	deals = '2',
	contacts = '3',
	companies = '4',
}

export const defaultProductFieldKeys = [
	'owner',
	'id',
	'title',
	'product_category_id',
	'type',
	'article',
	'prices',
	'measurement_unit_id',
	'comment',
	'currency',
	'tax',
	'link',
	'availability',
	'is_active',
	'description',
	'quantity',
	'reserved_quantity',
	'remainder',
	'preview_image_id',
	'file_ids',
	'files',
];

export enum FieldType {
	STAGE = 'stage',
	STRING = 'string',
	TEXTAREA = 'textarea',
	INTEGER = 'integer',
	FLOAT = 'float',
	LIST = 'list',
	DATETIME = 'datetime',
	MONEY = 'money',
	LABEL = 'label',
	PHONE = 'phone',
	EMAIL = 'email',
	SOCIAL = 'social',
	LINK = 'link',
	BOOLEAN = 'boolean',
	USER_ID = 'user_id',
	PHOTO = 'photo',
	FILE = 'file',
	ADDRESS = 'address',
	LEGAL_DETAILS = 'legal_details',
	ENTITY_REFERENCE = 'entity_reference',
	UTM = 'utm',
	CUSTOM_LINK = 'customLink',
	DEALS_FILTER = 'deals_filter',
	TASKS_FILTER = 'tasks_filter',
	ID_COLUMN = 'id_column',
	REQUISITE = 'requisite',
	PRIORITY = 'priority',
	ENTITY_REFERENCE_TASKS = 'entity_reference_tasks',
}

export const unreadMessagesValue = 'unreadMessages';

export const AVAILABLE_ENTITY_TYPES = [
	'tasks',
	'comment',
	'crm',
	'company',
	'contact',
	'deal',
	'lead',
	'post',
	'task',
	'companies',
	'contacts',
	'deals',
	'leads',
];

export const staticEntities: IEntityMainData[] = [
	{
		id: 10001,
		title: 'Calls',
		table_name: 'calls',
		type: 'calls',
		sort: 10,
		title_singular: null,
		kanban: false,
		for_all_users: true,
		display_in_menu: true,
		activity_support: true,
		task_support: true,
		created_by: null,
		changed_by: null,
		created_at: Math.floor(Date.now() / 1000),
		updated_at: Math.floor(Date.now() / 1000),
	},
	{
		id: 10002,
		title: 'Products',
		table_name: 'products',
		type: 'products',
		sort: 10,
		title_singular: null,
		kanban: false,
		for_all_users: true,
		display_in_menu: true,
		activity_support: true,
		task_support: true,
		created_by: null,
		changed_by: null,
		created_at: Math.floor(Date.now() / 1000),
		updated_at: Math.floor(Date.now() / 1000),
	},
	{
		id: 10003,
		title: 'Tasks',
		table_name: 'tasks',
		type: 'tasks',
		sort: 10,
		title_singular: null,
		kanban: false,
		for_all_users: true,
		display_in_menu: true,
		activity_support: true,
		task_support: true,
		created_by: null,
		changed_by: null,
		created_at: Math.floor(Date.now() / 1000),
		updated_at: Math.floor(Date.now() / 1000),
	},
	{
		id: 10004,
		title: 'Tasks',
		table_name: 'activities',
		type: 'activities',
		sort: 10,
		title_singular: null,
		kanban: false,
		for_all_users: true,
		display_in_menu: true,
		activity_support: true,
		task_support: true,
		created_by: null,
		changed_by: null,
		created_at: Math.floor(Date.now() / 1000),
		updated_at: Math.floor(Date.now() / 1000),
	},
];

export const fieldForCalls: IField[] = [
	idColumn,
	{
		name: 'callType',
		code: 'call_type',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'call_type',
		sort: '',
		system_field: false,
		default_value: '',
		values: [
			{
				color: '',
				selected: false,
				sort: 0,
				title: 'outgoing',
				value: 'outgoing',
			},
			{
				color: '',
				selected: false,
				sort: 0,
				title: 'incoming',
				value: 'incoming',
			},
		],
	},
	{
		name: 'callStatus',
		code: 'ended_call_status',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'call_status',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'date',
		code: 'begin_time',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'call_date',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'clientPhone',
		code: 'client_phone',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'call_phone',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'responsibleId',
		code: 'responsible_id',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'user_id',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'record',
		code: 'record',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'call_record',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'baseCRMEntity',
		code: 'base_entity',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'call_entity_reference',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'duration',
		code: 'duration',
		required: false,
		editable: false,
		show: true,
		hidden: true,
		multiple: false,
		type: 'call_duration',
		sort: '',
		system_field: false,
		default_value: '',
	},
];

export const fieldsForTasks: IField[] = [
	{
		name: 'caseType',
		code: 'type',
		required: false,
		editable: false,
		show: false,
		hidden: true,
		multiple: false,
		type: 'list',
		system_field: true,
		sort: '',
		default_value: '',
		values: [
			{
				color: '',
				selected: false,
				sort: 0,
				title: 'task',
				value: 'task',
			},
			{
				color: '',
				selected: false,
				sort: 0,
				title: 'call',
				value: 'call',
			},
			{
				color: '',
				selected: false,
				sort: 0,
				title: 'meeting',
				value: 'meeting',
			},
			{
				color: '',
				selected: false,
				sort: 0,
				title: 'chat',
				value: 'chat',
			},
			{
				color: '',
				selected: false,
				sort: 0,
				title: 'message',
				value: 'email',
			},
		],
	},
	{
		name: 'taskTitle',
		code: 'title',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'string',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'eventStartDate',
		code: 'start_time',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'dateCheap',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'eventEndDate',
		code: 'end_time',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'dateCheap',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'status',
		code: 'status',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'status',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'priority',
		code: 'priority',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'priority',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'responsibleId',
		code: 'responsible_id',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'user_id',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'leadOrAgreement',
		code: 'leadOrDeal',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'customLink',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'contacts',
		code: 'contacts',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'customLink',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'company',
		code: 'company',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'customLink',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'dateOfCompletion',
		code: 'closed_at',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'dateCheap',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'created_at',
		code: 'created_at',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'dateCheap',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'dateOfUpdate',
		code: 'updated_at',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: false,
		type: 'dateCheap',
		sort: '',
		system_field: false,
		default_value: '',
	},
	{
		name: 'participants',
		code: 'participants',
		required: false,
		editable: false,
		show: true,
		hidden: false,
		multiple: true,
		type: 'user_id',
		system_field: false,
		sort: '',
		default_value: '',
	},
];
